# This is a basic workflow to help you get started with Actions

name: CI - Functions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main, production ]
    paths:
      - "packages/functions/**"

      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/functions

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: "packages/functions/yarn.lock"

      # Runs a single command using the runners shell
      - name: Install
        run: yarn install
      - name: Check Prettier
        run: yarn prettier:check
      - name: Check Eslint
        run: yarn eslint:check
      - name: Check Type
        run: yarn type:check
